baseURL = "http://example.org/"
languageCode = "en-us"
title = "DDS Lab Website"
theme = "airspace"


[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Publications"
    url = "/blog/publications"
  [[menu.header]]
    weight = 4
    name = "People"
    url = "/people"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Publications"
    url = "/publications"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Digital Data Streams Lab"
    subtitle = "Ourso College of Business<br/>Louisiana State University<br/><br/>Dipartimento di Economia e Management<br/>Università degli Studi di Pavia"

  [params.wrapper]
    enable = false
    title = "About us"
    italics = "A Digital Data Stream (DDS) is the continuous digital encoding and transmission of data describing a related class of events. Examples abound, from Tweets and Instagrams, to the geolocation of merchant ships or the movement of soccer players on the pitch.  We see digital data streaming as the newest evolution of computing - from batch and online processing of transactions to the continuous processing of streaming data. As with any historical shift, the opportunities for value creation are endless, and research must contribute to our understanding of the phenomenon. The mission of the DDS Lab is to be at the forefront of knowledge and understanding of DDS - from their generation and processing to their productive and strategic use."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "About Us"
    content = "A Digital Data Stream (DDS) is the continuous digital encoding and transmission of data describing a related class of events. Examples abound, from Tweets and Instagrams, to the geolocation of merchant ships or the movement of soccer players on the pitch.<br/>We see digital data streaming as the newest evolution of computing - from batch and online processing of transactions to the continuous processing of streaming data. As with any historical shift, the opportunities for value creation are endless, and research must contribute to our understanding of the phenomenon.<br/>The mission of the DDS Lab is to be at the forefront of knowledge and understanding of DDS - from their generation and processing to their productive and strategic use."
    [params.feature.button]
      caption = "View Works"
      url = "/publications"

  [params.call]
    enable = true
    title = ""
    paragraph = ""

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
